# Generated by Django 2.0.3 on 2018-12-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20181117_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
