# Generated by Django 2.0.3 on 2018-12-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_article_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
