# Generated by Django 2.0.3 on 2018-12-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_trend_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
