# Generated by Django 2.0.3 on 2018-12-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_trend_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleArticle',
            fields=[
                ('article_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('url', models.CharField(max_length=255)),
                ('tag', models.CharField(default=None, max_length=255, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='apis.Category')),
            ],
        ),
    ]
