# Generated by Django 2.0.3 on 2019-03-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_samplearticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='trend',
            name='raw_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
