# Generated by Django 2.0.3 on 2019-03-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_trend_raw_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleTrend',
            fields=[
                ('trend_id', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('approx_traffic', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('published_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='trend',
            name='raw_content',
        ),
    ]
