# Generated by Django 2.0.3 on 2019-05-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20190317_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='googletrend',
            name='lang',
            field=models.CharField(default='TH', max_length=100),
        ),
    ]
